- server/lobbyconnection.py
This is needed to ensure we're not calling .encode() on non-strings.
> add string conversion

- server/game_service.py
- server/lobbyconnection.py
- tests/unit_tests/test_lobbyconnection.py
The client discards games in the ENDED or INITIALIZING states.
A recentish server change seems to have greatly increased the
number of such games (or perhaps simply changed how the server
is reporting them so the client is now being told about them).
Due to a stupidity in the client, this causes it to freeze for a
rather long time when it gets a huge pile of junk games dumped
on it on startup. We can save ourself some resources by not doing
so anyway, so let's do that.
We should also make the client not be stupid.
Fixes client/348 from the server direction.
> Don't send games in the "closed" state to the client

- server/lobbyconnection.py
- server/player_service.py
- tests/integration_tests/test_server.py
- tests/unit_tests/test_lobbyconnection.py
This removes a state from the client's state machine: it
previously had to handle having a half-initialised player, then
getting the real information later.
The client can now initialise itself properly with "me" on
welcome. It also knows that it will get this before it gets any
player_info objects about anyone else, which comes in handy.
> Send complete player information for the connecting user

- server/game_service.py
- server/games/game.py
- tests/unit_tests/test_game.py
Not to be confused with the gameType field in the DB, which is
actually the victory condition. This particular field is always
zero.
> Prune unused gameType field from Game objects

- requirements.txt
- server/games/game.py
- tests/unit_tests/test_game.py
Games ending with timeout never seem to get marked dirty, thus never garbage collected?
Proposed fix for #142
> Call on_game_end when a game timeouts

- server/games/game.py
- tests/unit_tests/conftest.py
- tests/unit_tests/test_custom_game.py
- tests/unit_tests/test_game.py
* All players on same team is now considered uneven unless team 1 (ffa)
* Added help function add_players() which can add X players to a game
* Added test for CustomGame to assert that global mean value for a player is higher after a win.
* Added test to assert that mutual draw isn't triggered by only one player reporting it.
* Added test to ensure corrupted / missing stats doesn't prevent rating persistence
> Unittest fixes

- server/lobbyconnection.py
When encountering unparseable mod in db, skip and log an error
Dunno if this is the best kind of change, but if we assume that the mod table is kind of open to shenanigans from people submitting mods, I think it's good to have it.
Fixes #241, but I still believe we should also get rid of NULL icons.
I looked at the tests, but how would I mock up a db row containing an invalid mod entry?
> Make mod listing more robust

- server/games/game.py
Coop games just take longer to launch, 20s timeout is not enough.
There is a substantial number of people who can never host coop because anyone trying to join gets "Host has left the game" error. After debugging this with speed2 it turned out his games timed out.
> 20:50:11 < duk3luk3> why would coop take longer to host?
> 20:50:32 < icedreamer> It does
> 20:50:33 < speed2> dunno, updating more files? game loading more data?
> 20:50:47 < icedreamer> When I launch coop locally it takes nearly 5 times longer than launching normal
> 20:50:58 < icedreamer> Both launching from files on my SSD
> 20:51:07 < icedreamer> Normal FA takes <1s
> 20:51:21 < icedreamer> My coop shortcut takes at least 4 or 5s to launch up
Fixes: #197
> Increase timeout for launching coop games

- requirements.txt
aiohttp removed `aiohttp.post` in 1.4.4, need to pin until we can fix
it.
This is needed to make build work.
> Pin aiohttp==1.3.3

- server/gameconnection.py
It appears that in a scenario where a player leaves while we wait for the STUN connection, EstablishConnection ignores that and keeps trying to connect the player. If it succeeds, we add a GameConnection for a player that already left. We try to fix this behaviour here.
> 276 potentially fix zombie games

- server/game_service.py
- server/player_service.py
The server periodically fetches information like the list of featured
mods and the minimum client version from the database.
A sixty-minutes interval is not reasonable. This commit changes it to 10
minutes.
Fixes #280
> Decrease cron data update interval

- .travis.yml
- README.md
- scripts/run_tests_with_coverage.sh
- server/games/game.py
This most likely doesn't solve all issues of #273 but right now I really don't have time to dig into this.
As the DB field mapId is now nullable, we at least insert null instead of 0 now.
This should've been part of v0.6.1, unfortunately I wasn't aware of that I didn't merge it.
> Fix #273 don't insert mapId = 0

- server/gameconnection.py
- server/games/game.py
- tests/unit_tests/conftest.py
- tests/unit_tests/test_game.py
- tests/unit_tests/test_gameconnection.py
Treat GameResult message in GameConnection as a signal that a player has
ended his sim. Track these ending sims in Game; once all remaining
GameConnections are marked as ended and the game is in a Live state,
mark the Game as (sim-wise) ended and set its end time.
Fixes #289.
Signed-off-by: Igor Kotrasinski <ik345186@students.mimuw.edu.pl>
> Track and remember game (sim) end

- server/lobbyconnection.py
The information dump sent to the client after it logs in includes
friends and foes (`social` message) and currently hosted / running
games.
Sending the `social` message first means friend/foe information will be
available for the client so it can use it for coloring the hosted game
display.
Making this trivial change on the server avoids adding complex logic to
the client to update the display of games after social information is
received or holding back the display of games completely until that
point.
Fixes https://github.com/FAForever/client/issues/845
> Send social info before games info

- server/player_service.py
Prevents the server from throwing an exception and ejecting players when it can't check which versions are allowed due to the database being empty
> Fixed no client versions in the db preventing players to connect

- server/__init__.py
- server/config.py
You can now disable statsD via an env/or the configuration file so that server set up is easier for testing.
It's replaced by a mock object when disabled.
> StatsD is now optional

- server/gameconnection.py
- server/games/game.py
- server/ladder_service.py
- tests/unit_tests/test_game.py
- tests/unit_tests/test_gameconnection.py
Prevents database errors on game renaming.
Client displaying of game names is not affected.
> Filtering non-latin names

- server/__init__.py
- server/fake_statsd.py
- tests/integration_tests/test_servercontext.py
Not sure fake_statsd.py is in the right place
nor named the right way!
This adds a dummy class to emulate statsD connection (magic.mock() creates a memory leak on the long run)
> Fixed memory leak when StatsD is disabled

- server/stats/game_stats_service.py
There seems to be shady stuff going on with that army_result
When put to 0 a lot of tests about achievements start failing, but somehow it doesn't feel so related. I wonder if those tests ran in the past or if they were simply skipped because of the way game_stats_service returns without exceptions when encountering weird results.
> [WIP] Army stats fix

- server/lobbyconnection.py
- server/matchmaker/matchmaker_queue.py
- tests/unit_tests/test_matchmaker_queue.py
Make the client responsible for creating the `Search` object using it's constructor instead of proxying arguments to in from `search()`.
> Refactored search to remove redundant parameter 'player'

- requirements.txt
- server/abc/base_player.py
- server/factions.py
- server/stats/game_stats_service.py
- tests/unit_tests/test_game_stats_service.py
- tests/unit_tests/test_players.py
Faftools was only being used for the faction enum. The python API is no longer used and the python client doesn't use faftools either, so this was the last remaining active use of faftools. Better to just move the Faction enum into this repository. 
This should also remove the `lupa` dependency which will make the server easier to build.
Also cleaned up imports a little bit.
> Remove faftools

- .travis.yml
- tests/conftest.py
- tests/unit_tests/test_gameconnection.py
- tests/unit_tests/test_lobbyconnection.py
With the v64 image being done, we can now un-skip the two tests that were waiting for the updated `test-data.sql` file. Hooray!
> Un-skip tests that were waiting on test data from v63

- server.py
- server/__init__.py
- server/game_service.py
- server/gameconnection.py
- server/games/__init__.py
- server/games/game.py
- server/games/game_mode.py
- server/ladder_service.py
- server/lobbyconnection.py
- server/matchmaker/matchmaker_queue.py
- server/matchmaker/search.py
- server/player_service.py
- server/protocol/qdatastreamprotocol.py
- server/servercontext.py
- tests/conftest.py
- tests/integration_tests/test_server.py
- tests/integration_tests/test_servercontext.py
- tests/unit_tests/conftest.py
- tests/unit_tests/test_gameconnection.py
- tests/unit_tests/test_games_service.py
- tests/unit_tests/test_ladder.py
- tests/unit_tests/test_lobbyconnection.py
- tests/unit_tests/test_matchmaker_queue.py
Trying to decouple the services as much as possible. There are a lot of cyclic dependencies that should be removed. Some are handled as weak references, but most are owning such as `LobbyConnection` <-> `GameConnection`
> [Refactor] Remove unnecessary dependencies between services

- server/lobbyconnection.py
- tests/conftest.py
- tests/data/test-data.sql
- tests/integration_tests/conftest.py
- tests/integration_tests/test_matchmaker.py
- tests/integration_tests/test_server.py
- tests/integration_tests/testclient.py
- tests/unit_tests/test_ladder.py
Make the integration tests actually check something. This will be an OK way of testing things which are otherwise hard to do with unit tests because of the mocks. For example checking that a game's default title is set correctly if the host doesn't specify a title.
Added integration tests for:
* Queueing a ladder match
* Players banned form ladder receive the 'you are banned' message
* Hosting a game with missing or empty fields
I also added a test-data.sql file to this repo so that we don't need to insert data in the test themselves, and don't need to submit PR's to Faforever/db just to add some test data.
> Integration tests update

- server/db/models.py
- server/lobbyconnection.py
- tests/data/test-data.sql
- tests/unit_tests/test_lobbyconnection.py
Fixes #414 
The fix was to remove the `timed()` decorator since it isn't designed to work on async functions. I took the opportunity to add a couple of tests and to rewrite the sql statements with sqlalchemy.
> Issue/#414 Fix friends/foes not being saved in database

- server/gameconnection.py
Adding these mostly for documentation purposes. These are messages sent by the client which the server has historically ignored. This will also prevent these messages from generating warnings in the server log file.
> Added Chat and GameFull message handlers

- .gitignore
- server/gameconnection.py
- server/lobbyconnection.py
- server/player_service.py
- tests/data/test-data.sql
- tests/integration_tests/conftest.py
- tests/integration_tests/test_matchmaker.py
- tests/unit_tests/test_gameconnection.py
- tests/unit_tests/test_ladder.py
- tests/unit_tests/test_player_service.py
Closes #435 
Avatar query was not taking into account which avatar was selected. Note that if somehow a player manages to select multiple avatars, only one of them will be taken.
The lobbyconnection was also doing some extra input validation which was not compatible with the py client, (py client sends factions as numbers while java client sends the string of the faction name).
The modvault command was trying to create icon URL's even when the `icon` field was null.
Automatic teamkill reports (GPGNet `TeamkillHappened`) were being ignored. These will now be inserted to the DB. Note that every player in a game will send one of these.
Included tests for both of these issues.
> Hotfix 9.30: Fix avatars and py client matchmaking

- server/ladder_service.py
I believe at some point this loop encounters an error and the coroutine crashes, resulting in people still being matched by `MatchmakerQueue`, but no games being started.
> Fix: Ensure that LadderService continues to process matches

- server/lobbyconnection.py
- tests/data/test-data.sql
- tests/integration_tests/conftest.py
- tests/integration_tests/test_modvault.py
Mods that have a `null` value for their `icon` would cause the `modvault` command to crash with the following exception:
```
ERROR    Jun 21  15:04:30 LobbyConnection                Error handling table_mod row (uid: 022E3DB4-9C00-5ED7-9876-4866D316E014)
Traceback (most recent call last):
File "/code/server/lobbyconnection.py", line 801, in command_modvault
thumbstr = urllib.parse.urljoin(config.CONTENT_URL, "faf/vault/mods_thumbs/" + urllib.parse.quote(icon))
File "/usr/local/lib/python3.6/urllib/parse.py", line 805, in quote
return quote_from_bytes(string, safe)
File "/usr/local/lib/python3.6/urllib/parse.py", line 830, in quote_from_bytes
raise TypeError("quote_from_bytes() expected bytes")
TypeError: quote_from_bytes() expected bytes
```
> Fix command_modvault exception

- Pipfile
- Pipfile.lock
This was locked before because we were using a deprecated API. As that has been replaced with the new way of doing things, we no longer need to keep this package outdated.
A note from the docs, that `aiodns` is recommended to speed up DNS resolution.
> Unlock the aiohttp dependency

- server/lobbyconnection.py
- tests/data/test-data.sql
- tests/integration_tests/test_matchmaker.py
Apparently this table has never been used. If we really need a ban for only matchmaking in the future, we can use the same `ban` table as for other bans, and add another scope for matchmaking.
Removing database table dependencies will make it easier to transition to a new schema.
Closes https://github.com/FAForever/db/issues/109
> Remove check for matchmaker_ban table

- server/__init__.py
- server/matchmaker/matchmaker_queue.py
- tests/integration_tests/test_matchmaker.py
- tests/integration_tests/test_server.py
> Only tell authenticated clients about matchmaker info

- server/config.py
- server/matchmaker/__init__.py
- server/matchmaker/algorithm.py
- server/matchmaker/matchmaker_queue.py
- server/matchmaker/pop_timer.py
- tests/integration_tests/conftest.py
- tests/integration_tests/test_matchmaker.py
- tests/unit_tests/conftest.py
- tests/unit_tests/test_matchmaker_queue.py
The previous queue pop time calculations were pretty arbitrary. This method is based on trying to achieve a certain number of players in the queue for matching,  based on the observed rate of players queuing for matchmaker. In other words, the queue pop timer tries to adjust the pop times so that there are always a constant number of people in the queue.
> Smarter queue pop times

- server/__init__.py
- server/matchmaker/algorithm.py
- server/protocol/qdatastreamprotocol.py
- tests/unit_tests/test_matchmaker_queue.py
- tests/unit_tests/test_matchmaker_queue_algorithm.py
See issue #487.
Two main changes:
1. Matchmaking graph for stable marriage will include top five matches for every player *of those who would accept the match* 
2. Minimum acceptable match quality is calculated as 80% of quality in a game against yourself, not hard-coded in `_deviation_quality`
> Fix players with high deviations not getting 1v1 ladder matches

- Dockerfile
- Pipfile
- Pipfile.lock
- scripts/run_tests_with_coverage.sh
I submitted a PR to `aiomysql` to fix the deprecation warnings https://github.com/aio-libs/aiomysql/pull/403 which was merged, but hasn't been deployed as apparently the people with the ability to do so have disappeared into the void. So instead, we can just install from git to get the latest version
> Install aiomysql from git and re-enable warnings

- server/game_service.py
- server/lobbyconnection.py
- tests/integration_tests/test_server.py
- tests/unit_tests/test_lobbyconnection.py
Doesn't completely remove the dependency on `game_featuredMods` table as the server still needs to convert mod names into mod id's for inserting into `game_stats` (lobbyconnection#L748).
> Don't send mod list to the client

- server/lobbyconnection.py
- tests/integration_tests/test_matchmaker.py
- tests/integration_tests/test_server.py
Need this so the client can display the queue time immediately.
https://github.com/FAForever/downlords-faf-client/pull/1364
> Add endpoint for requesting matchmaker info

- server/db/__init__.py
- tests/utils.py
This makes the log slightly less informative, but no longer leaks
sensitive info, so we can actually access the thing without huge hassle.
Signed-off-by: Igor Kotrasinski <i.kotrasinsk@gmail.com>
> Don't echo DB operations to log

- server/lobbyconnection.py
- tests/unit_tests/test_lobbyconnection.py
Since client work is being done on this anyways, might as well do it right. See FAForever/downlords-faf-client#1472
Related to #444.
Closes #499.
> Let client do localization for Close FA message

- server/gameconnection.py
- server/games/game.py
- server/games/game_results.py
- server/games/ladder_game.py
- server/stats/game_stats_service.py
- tests/conftest.py
- tests/unit_tests/conftest.py
- tests/unit_tests/test_game.py
- tests/unit_tests/test_game_stats_service.py
- tests/unit_tests/test_gameconnection.py
- tests/unit_tests/test_laddergame.py
This moves the logic determining game's outcome for players into a separate class. Methods for choosing an outcome from multiple reports are merged into one. TODO: discuss if the method chosen is appropriate.
The PR is based on top of #494, so it has some extra commits.
> Clean up game outcome handling

- server/__init__.py
- server/api/oauth_session.py
- server/control.py
- server/game_service.py
- server/gameconnection.py
- server/games/game.py
- server/geoip_service.py
- server/ladder_service.py
- server/lobbyconnection.py
- server/matchmaker/search.py
- server/protocol/gpgnet.py
- server/protocol/protocol.py
- server/protocol/qdatastreamprotocol.py
- server/servercontext.py
- server/timing/__init__.py
- server/timing/timer.py
- tests/conftest.py
- tests/data/test-data.sql
- tests/integration_tests/conftest.py
- tests/integration_tests/test_matchmaker.py
- tests/integration_tests/test_modvault.py
- tests/integration_tests/test_server.py
- tests/integration_tests/test_servercontext.py
- tests/unit_tests/conftest.py
- tests/unit_tests/test_gameconnection.py
- tests/unit_tests/test_ladder.py
- tests/unit_tests/test_lobbyconnection.py
This refactors the old callback interface for message sending to use async/await native instead. Not only is the coroutine interface cleaner and more intuitive, it also helps to ensure that the code behaves as we expect it to (for instance backpressure handling) without us needing to even think about edge cases.
Also adds a few additional test cases.
> Refactor message sending interface to be a coroutine

- scripts/pipenv_run_tests.sh
- scripts/run_tests_with_coverage.sh
- server/__init__.py
- server/decorators.py
- server/fake_statsd.py
- server/game_service.py
- server/gameconnection.py
- server/ice_servers/nts.py
- server/lobbyconnection.py
- server/matchmaker/algorithm.py
- server/matchmaker/matchmaker_queue.py
- tests/integration_tests/test_servercontext.py
- tests/unit_tests/test_decorators.py
- tests/unit_tests/test_gameconnection.py
- tests/unit_tests/test_matchmaker_queue.py
Removing unnecessary parentheses, test for membership should be "not in", typo fixes, indentation/spacing, changing from use of deprecated functions to non-deprecated functions, capitalization, fixing syntax of Bash scripts, line length, added "await" to coroutine that is not awaited.
> General code cleanup

- server/config.py
- server/geoip_service.py
- tests/unit_tests/test_geoip_service.py
Updated the geoip url and added a license key parameter. The license key does not have a default and must be set by a server admin in order for the new database to be downloaded.
The database is now served via a `tar.gz` which contains a copyright and a license text as well as the database. The server now downloads the archive and compares its checksum against the md5 hash available at the same url. Once the archive has been successfully downloaded, the database file is extracted from the archive and copied over the old version of the file (if it exists).
Closes #513
> Issue/#513 New geoip database download URL

- server/lobbyconnection.py
- tests/integration_tests/test_admin.py
- tests/integration_tests/test_server.py
- tests/unit_tests/test_lobbyconnection.py
While merging a different PR I noticed that I forgot to await these and there were no tests to catch this error. So now I'm fixing it and adding some tests.
I also refactored the `join_channel` command. I noticed that the logic would not allow admins to use that command (only mods without admin power could use it) and that the method of extracting the user_id's seemed questionable. Before the message would have had to look like:
```json
{
"user_ids": [1, 2, 3],
1: 1,
2: 2,
3, 3
}
``` 
which seems insane to me and I'm not even sure is valid json, so now it just looks like:
```json
{
"user_ids": [1, 2, 3]
}
```
> Await async sending functions in command_admin

- server.py
- server/player_service.py
- server/stats/game_stats_service.py
- tests/unit_tests/test_game_stats_service.py
- tests/unit_tests/test_player_service.py
I was wondering why the test server stopped sending the usual shutdown message... Also changed the tests to use `create_autospec` so this sort of thing doesn't get missed in the future.
> Fixed some more places where coroutines were not awaited

- server/games/game.py
- server/games/game_rater.py
- server/games/game_results.py
- tests/unit_tests/test_game.py
- tests/unit_tests/test_game_rater.py
Now that I've spent some more time analysing game results, I realized that our game rating consistency checks were not quite right. Each army should have a consistent result reported (e.g. each player reports that army 1 was defeated) but each player on a team will not necessarily have the same game result. For instance if a player dies, but their teammates still carry them to victory, then the winning team will have at least one player with a `defeat` result and at least one player with a `victory` result. For this reason, `victory` results take precedence over all other results.
I also snuck in some other refactors like fixing functions that didn't exist or using `is` operator for numeric comparison instead of `==`. All things that I missed when reading the code on github, but my linter …
> Game Rating: Clean up some formatting and faulty logic that I missed before

- server/lobbyconnection.py
- server/protocol/gpgnet.py
- tests/unit_tests/test_lobbyconnection.py
Pulling some stuff out of #428 that doesn't need to wait. I think these changes are backwards compatible with the current client. A client implementation exists on the gw-on-ice branch: https://github.com/FAForever/downlords-faf-client/commit/97f72147d48537ca98a7cc37faad591f612fc6b8
> Send game configuration options to the client in game_launch

- server/gameconnection.py
- server/lobbyconnection.py
- server/protocol/qdatastreamprotocol.py
- server/servercontext.py
- tests/unit_tests/test_gameconnection.py
- tests/unit_tests/test_protocol.py
The server logs are plagued with the following error:
```
Traceback (most recent call last):
File "/code/server/__init__.py", line 148, in do_report_dirties
await asyncio.gather(*tasks)
File "/code/server/servercontext.py", line 56, in broadcast_raw
await asyncio.gather(*tasks)
File "/code/server/protocol/qdatastreamprotocol.py", line 150, in send_raw
await self.writer.drain()
File "/usr/local/lib/python3.6/asyncio/streams.py", line 339, in drain
yield from self._protocol._drain_helper()
File "/usr/local/lib/python3.6/asyncio/streams.py", line 214, in _drain_helper
assert waiter is None or waiter.cancelled()
AssertionError
```
It appears that this is caused by `drain` being awaited by multiple coroutines. As a result this is non-trivial to reproduce on the test server as it requires a lot …
> Asyncio drain fix

- server/__init__.py
- server/async_functions.py
- server/gameconnection.py
- server/lobbyconnection.py
- server/player_service.py
- server/servercontext.py
- tests/conftest.py
- tests/integration_tests/conftest.py
- tests/integration_tests/test_server.py
- tests/integration_tests/test_servercontext.py
- tests/unit_tests/test_async_functions.py
- tests/unit_tests/test_lobbyconnection.py
`broadcast_raw` is now guaranteed not to raise any `ConnectionError`s. We really don't care if our broadcast failed to a player because they closed their connection before we finished writing the message. 
Also ignored connection errors in some other places where a manual broadcast was happening such as admin commands.
> Bugfix: Handle connection errors

- server/__init__.py
- server/async_functions.py
- server/lobbyconnection.py
- server/servercontext.py
- tests/unit_tests/test_lobbyconnection.py
When broadcasting ignore all exception classes. Possible exceptions that we tend to run into:
-  ConnectionError: When a user disconnects in a mostly normal way
- TimeoutError: When the connection times out.
- OSError (no route to host)
In `do_report_dirties` wrap each broadcast in its own try/except block so that a failure in one block will not prevent the other logic from running.
Rewrite `gather_without_exceptions` using `asyncio.as_completed`. This makes it a lot easier to understand.
> Fix exception handling

- server/games/game_rater.py
- tests/unit_tests/test_game_rater.py
The `GameRater` would refuse to rate two-player games if one player had chosen a (numbered) team, while the other player remained teamless (the FFA team "-").
This should fix it.
Includes some further unit tests on various distributions of players on FFA and actual teams.
> Two player FFA

- server/gameconnection.py
- server/lobbyconnection.py
The trace messages will log the username if the user has logged in, otherwise they'll log the session id.
```
DEBUG    Feb 26  19:12:56 ServerContext                  ServerContext(LobbyServer): Client connected
DEBUG    Feb 26  19:12:56 LobbyConnection                LobbyConnection initialized
TRACE    Feb 26  19:12:58 LobbyConnection                << 2715862830: {'command': 'ask_session', 'user_agent': 'askaholics-faf-cli', 'version': '1.0.0'}
TRACE    Feb 26  19:12:58 LobbyConnection                >> 2715862830: {'command': 'notice', 'style': 'info', 'text': 'You are using an unofficial client version! Some features might not work as expected. If you experience any problems please download the latest version of the official client from <a …
```
> Issue/#535 Add username or session id to trace messages

- patcher.py
- server/config.py
- server/db/models.py
- server/game_service.py
- server/gameconnection.py
- server/lobbyconnection.py
- server/matchmaker/algorithm.py
- server/matchmaker/search.py
- server/stats/unit.py
- tests/unit_tests/conftest.py
- tests/unit_tests/test_achievement_service.py
- tests/unit_tests/test_game.py
- tests/unit_tests/test_game_rater.py
- tests/unit_tests/test_ice.py
- tests/unit_tests/test_matchmaker_queue.py
- tests/unit_tests/test_matchmaker_queue_algorithm.py
I thought it's easier to run `flake8` on new PRs, if I first get rid of most of the things on develop that it takes issue with (the majority of which I probably introduced myself...).
the only things left now are:  
`E501` line width
`E999` syntax that flake8 doesn't understand
`E722` bare excepts (that I didn't want to touch here)
(and a few special cases in the tests)
I'm not sure whether we want to adhere to `E252` that puts whitespace around `=` in default parameters that use typing, like 
```python
#what we had before:
def func(x: int, y: int=0):
pass
def func(x: int, y: int = 0):
pass
```
> Placating flake8

- .gitignore
- Pipfile
- Pipfile.lock
- server/matchmaker/algorithm.py
- server/matchmaker/matchmaker_queue.py
- server/matchmaker/search.py
- tests/conftest.py
- tests/unit_tests/conftest.py
- tests/unit_tests/test_game.py
- tests/unit_tests/test_matchmaker_queue.py
- tests/unit_tests/test_matchmaker_queue_algorithm.py
Turns out that matchmaking performance is dominated by the creation of the `MatchingGraph`. Most of this comes from calls to `trueskill` for determining the edge weights but there were a few other instances of unnecessary work being performed.
- Precompute quality against yourself. Easily eliminates 10's of calls to trueskill per search.
- Cache calls to `Search.quality_with` for the duration of `MatchingGraph` creation. This significantly reduces the amount of trueskill calls made.
- Only compute quality in one direction since quality is symmetric (`self.quality_with(other) == other.quality_with(self)`)
For a MatchingGraph on 30 searches, these improvements bring the time of `make_matches` from 2.294 per call down to 0.148 per call. Easily a 10x speedup.
Before:
```
35261689 function …
```
> Improve matchmaking performance

- server/config.py
- server/protocol/qdatastreamprotocol.py
- server/servercontext.py
Refactor `ServerContext.broadcast` so that it only performs json and QDataStream encoding once per message (as opposed to once per connection per message).
> Improve broadcast performance

- server.py
- server/config.py
So we can figure out what needs to be optimized.
I think I will make the profiler only run when we have less than 1100 users online. I'd like to get profiling data when there are as many users as possible, but we don't want to add the performance cost of profiling during the highest load times.
> Added intermitent profiling

- server/factions.py
- server/ladder_service.py
- server/players.py
- tests/integration_tests/test_matchmaker.py
StartSpot and Army are supposed to be the same (currently this is overwritten by the autolobby code anyways) and the Faction option needs to be an `int` otherwise the sql query will fail.
> Tweak automatch options

- server/games/game.py
- server/games/game_rater.py
- server/games/game_results.py
- server/games/ladder_game.py
- server/stats/game_stats_service.py
- tests/unit_tests/test_game.py
Now `Game.persist_results` writes the `GameOutcome` for every single player to the new `result` column of `game_player_stats`, according to `Game.outcome` at the time of the call.
Also introduces new `GameOutcome.CONFLICTING`, which is treated as `UNKNOWN` for rating purposes, so this shouldn't change any rating decisions.
> Write GameOutcome to db in Game.persist_results.

- server/__init__.py
- server/config.py
- server/lobbyconnection.py
- server/protocol/qdatastreamprotocol.py
- server/servercontext.py
- tests/integration_tests/test_load.py
- tests/integration_tests/test_servercontext.py
Broadcasting is by far the most expensive single operation that the server does. There is also no good way of handling backpressure in the broadcasts since we can't just stop broadcasting updates to certain players. 
It seems that calling drain for each connection and each message adds significant overhead, so by writing synchronously and not waiting for the messages to be sent we save ourselves a lot of calls to asyncio machinery which ultimately doesn't gain us anything anyways. 
This is how everything was done in v1.2.
> Performance: Don't await broadcasts

- server/api/api_accessor.py
- tests/integration_tests/conftest.py
- tests/unit_tests/test_api_accessor.py
We know there is some error happening, but we don't know what it is because the ApiAccessor doesn't raise an exception for it.
> Log API error

- tests/integration_tests/test_matchmaker.py
Travis build failed because it barely didn't wait long enough. This should ensure that the database change has always been persisted by the time the test checks it.
> Make matchmaker test more reliable

- server/games/game.py
- server/lobbyconnection.py
- tests/unit_tests/conftest.py
- tests/unit_tests/test_game.py
Might fix #225.
When doing testing of the game result issue and struggling with getting the ICE adapter to connect two machines on the same network I noticed what might be causing the display of extra players in lobby. 
The server would count a player as "in-lobby" as soon as they sent `GameState: Lobby` meaning as soon as their game made it to the `connecting to host` screen. This means if someone was trying to join a lobby, but could not connect to the host, it would still falsely bump the `num_players` which might cause the lobby to appear full when it was actually one player short. 
It seems like the only way to detect if a player has successfully connected to the host is by the host sending `PlayerOption` commands for them. So we can use the presence of player options as an indicator …
> Only show players if they've managed to connect

- server.py
- server/core/__init__.py
- server/core/dependency_injector.py
- server/core/service.py
- tests/unit_tests/core/test_dependency_injector.py
Makes it easier for us to add new services and to change the parameters to service constructors. 
Any class inheriting from `Service` will be instantiated as a singleton object automatically. The class can take other `Service`'s as arguments so long as there is no cyclic dependency between services. 
Any class inheriting from `Service` is provided two server lifecycle hooks: `initialize` and `shutdown` which can be used to perform setup and cleanup actions for the service.
> Automatic service instantiation

- .travis.yml
- tests/data/test-data.sql
- tests/unit_tests/test_ladder.py
Needed to use the new rating tables.
Required a few adaptations of the unit tests, since map id 0 was removed by a previous migration, which I wanted to keep out of from the rating service PR.
> Bump faf-stack version to v20.4.18

- server/lobbyconnection.py
- tests/integration_tests/test_game.py
- tests/unit_tests/test_lobbyconnection.py
One of the things we noticed during TMM testing was that the games would show up in the custom games tab and could be joined through the normal method. However the game was pretty broken after that point, with the player who joined in this way showing up as playing the nomads faction, but also being set as observer. 
As it turns out, the server hasn't been checking whether player initiated game joins are actually valid with respect to init mode. It is possible that some of the rare ladder errors involving players having the nomads faction were caused by some client bugs / inconsistent state allowing them to join ladder games through the custom games tab.
> Check init mode in command `game_join`

- integration_tests/fafclient.py
- integration_tests/test_game.py
- server/gameconnection.py
- server/lobbyconnection.py
- tests/integration_tests/test_game.py
Should be able to solve #580 with this small change and another really small change in the FA code (sending `GameState: Ended` when `SafeQuit` is triggered). I think this is a better solution (because its so much simpler) than what I described in #587.
When investigating the `SafeQuit` issue, I noticed that `GameConnection` objects would not be deleted after games ended because `lobby_connection` would still hold a reference to them. This reference would only be removed once a new game was started or the player disconnected from the server. Since `GameConnection` holds a strong reference to `Game` this also means that `Game` objects would not be deleted for a possibly very long time.
Another possible solution would be to make `LobbyConnection` only hold a weak reference to …
> Unset lobby_connection reference to game_connection on abort

- server/games/game.py
- tests/data/test-data.sql
- tests/integration_tests/test_game.py
- tests/unit_tests/test_game.py
Adds in a check for if the map is a generated map by checking whether the start of the map name matches the map generator template name. If the map is marked as generated it will not be given a BAD_MAP Validity State.
Closes #617
> Issue/#617 Add check for generated map

- server/lobbyconnection.py
- tests/integration_tests/test_server.py
Hej, i created a bunch of games using some silly tool i made and made sure they were correct in the client. All seems ok. I could not find any places where the &amp; i mean \&amp; would pop up though. Nice to see that html injection works in this box.
Checked the client (a little bit) for any unescape code, but java isn't really my cup of tea.
Fixes #282
> Issue/#282 Game titles seem to be quoted needlessly

- server/ladder_service.py
- tests/unit_tests/test_ladder_service.py
The code for initializing hardcoded queues would also start any queues loaded from the database at server start time
> Fix matchmaker queue double initialization

- server.py
- server/__init__.py
- server/players.py
- server/protocol/__init__.py
- server/protocol/protocol.py
- server/protocol/qdatastream.py
- server/protocol/simple_json.py
- server/servercontext.py
- tests/integration_tests/conftest.py
- tests/integration_tests/test_server_instance.py
- tests/unit_tests/test_players.py
- tests/unit_tests/test_server_instance.py
Refactors the server broadcasting code so that multiple ServerContext's can be run correctly at the same time. This will allow us to start working on a v2 version of the protocol which can concurrently with the legacy protocol. As a sample I've added a `SimpleJsonProtocol` class that sends each message as a json object followed by a newline.
I think we should try to transition to the new protocol incrementally. As a first step, we can swap out the "transport" or "wire" layer from `QDataStream` to `Json`, and keep everything else the same. We could implement this in the client and start using it immediately, which would cut the amount of network traffic in half (due to the legacy protocol using utf-16 encoding instead of utf-8). There isn't really a down side to doing this, as we can keep …
> Support multiple servercontexts

- server/ladder_service.py
- server/lobbyconnection.py
- server/matchmaker/matchmaker_queue.py
- tests/unit_tests/test_ladder_service.py
- tests/unit_tests/test_matchmaker_queue.py
The interface for searching/cancelling is now asymmetric. 
- Searches are started on a list of players and one queue name
- Searches are cancelled for one player and one queue name (or all queues)
This should allow pretty trivial integration with the party system. 
- When a player starts a search, call `start_search` with the players entire party
- When a player cancels a search, call `cancel_search` with just the requesting player
Permissions still need to be handled by the caller of `LadderService` (which is always `LobbyConnection`)
> Rework ladder search internals/interface

- Pipfile
- Pipfile.lock
- server/lobbyconnection.py
- tests/data/test-data.sql
- tests/integration_tests/test_login.py
- tests/integration_tests/test_server.py
- tests/unit_tests/test_lobbyconnection.py
Hi. This is my first PR to FAF.
This PR addresses #639: "Show ban duration to user with higher resolution." I think it would be better to implement #640 in the long term, but I don't know how to do that yet and this PR still gives an improvement.
The tests outline the new behaviour, and test more of what was already there. A temporarily banned user will now see a message saying:
```
You are banned from FAF for 1 day and 8.5 hours.
Reason :
[ban reason here]
```
I haven't actually been banned myself 😇 but this seemed like a good first contribution.
Closes #639.
> Issue/#639 Show ban duration to user with higher resolution

- server/lobbyconnection.py
- tests/unit_tests/test_lobbyconnection.py
Luckily since the server is located in Germany (at most UTC+2) this hasn't had any meaningful impact on ban durations. Also I would imagine that Travis builds are run in Germany too, so our tests wouldn't pick up on this either. It's just kindof funny that I keep finding these timezone discrepancies.
Also reformatted some stuff long lines.
> Use UTC instead of local timezone for determining remaining ban time

- tests/integration_tests/test_game.py
Closes #634. See discussion on linked issue.
I am still unsure about the underlying cause for the additional `game_info` message with `'state': closed`.
> Make test_gamestate_ended_clears_references more robust

- server/games/coop.py
- server/games/game.py
This commit closes #636. It restructures the validity checks that are performed on games. It starts taking advantage of the OOP setup of Game classes. Child classes of Game can redefine the `_validate_game_mode_settings` method to set custom game validity rules.
As discussed in #636 there is probably more tidyup to be done of these classes and how featured mods/game types work. I'm leaving that for later because I don't feel confident attempting it yet.
> Issue/#636 Refactor game validity checks

- integration_tests/test_matchmaking.py
- server/__init__.py
- server/games/game.py
- server/games/typedefs.py
- server/lobbyconnection.py
- server/rating.py
- tests/integration_tests/test_game.py
- tests/integration_tests/test_server.py
- tests/unit_tests/test_game.py
- tests/unit_tests/test_lobbyconnection.py
Might need to refactor/rename some stuff (I'm a bit tired ATM) but I think it should work.
The host can now optionally send `rating_min` and `rating_max` fields as well as `enforce_rating_range` in the game host message. These fields are echoed back in the `game_info` message so that the client can display them. If `enforce_rating_range` is true, then the game will not be sent to players outside of the rating range. Note that the rating range can be unbounded, so for example to create a 1000+ game you would send `rating_min: 1000` and either omit `rating_max` or set it like `rating_min: null`. Also be aware that it will use the displayed rating (mean - 3*dev) for the game's rating type. For custom games this is currently always GLOBAL, but who knows what might be added in the future. …
> issue/#649 Allow host to set rating range limitations to game

- server/players.py
- server/weakattr.py
- tests/unit_tests/test_players.py
- tests/unit_tests/test_weakattr.py
I stumbled across this `WeakAttribute` implementation while looking up something unrelated and realized that we actually have a use case for it. This will also make it easier to add weak references on other objects too, not just Player. I also refactored a few other things in Player while I was at it.
> Refactor weakrefs in Player object

- server/config.py
- server/games/game.py
- server/games/ladder_game.py
- tests/unit_tests/test_game_rating.py
Gives the possibility to decide the outcome of 1v1 ladder games by score instead of by reported result, as it was a year ago.
I added a config variable, so that this can be turned on and off dynamically (e.g. for testing new game patches on the test server).
I hope that the game still reports scores as it did and that that didn't change with recent patches?
Could make this override for all 1v1 games, but I thought I'd rather have as little scope as possible.
Addresses issue #580 but should be regarded a temporary fix.
> Add outcome override for ladder 1v1 games

- integration_tests/fafclient.py
- integration_tests/test_game.py
- integration_tests/test_matchmaking.py
This should generate entries in matchmaker_queue_game
> Add test to fully simulate ladder game

- integration_tests/fafclient.py
- server/lobbyconnection.py
- server/rating_service/rating_service.py
- tests/unit_tests/test_lobbyconnection.py
We were not able to reproduce the issue yet, but in theory it might be possible that the await statement on sending the warning to old player connections could prevent the welcome message from being delivered to the new connection.
Uses the `write` variant (instead of `send`) when notifying the old connection of the new login.
> Hopefix for infinite login

- server/ladder_service.py
- tests/integration_tests/test_matchmaker.py
During the TMM test we saw a lot of this exception:
```
ERROR    Oct 04  18:19:01 LobbyConnection                'ladder1v1'
Traceback (most recent call last):
File "/code/server/lobbyconnection.py", line 147, in on_message_received
await handler(message)
File "/code/server/lobbyconnection.py", line 789, in wrapper
return await func(self, message)
File "/code/server/lobbyconnection.py", line 856, in command_game_matchmaking
self.ladder_service.cancel_search(self.player, queue_name)
File "/code/server/ladder_service.py", line 207, in cancel_search
self._cancel_search(initiator, queue_name)
File "/code/server/ladder_service.py", line 213, in _cancel_search
cancelled_search = self._searches[initiator][queue_name]
KeyError: 'ladder1v1'
```
Which would cause players to be disconnected if their …
> Ignore cancellation of non-existing search without error

- server/games/game.py
- server/ladder_service.py
- tests/integration_tests/test_game.py
- tests/integration_tests/test_matchmaker.py
- tests/integration_tests/test_teammatchmaker.py
- tests/unit_tests/test_ladder_service.py
Adds logic for sending `match_cancelled` messages if the matchmaker game doesn't start within about a minute. This should fix point 4 mentioned here https://github.com/FAForever/downlords-faf-client/pull/1778#issuecomment-660403082. 
Seems like some of the mocking code in the tests was not working correctly, and they were waiting for 30 seconds for the game timeout to trigger before passing. Now that's been fixed and the tests run about 30 seconds faster.
Closes #621
> Issue/#621 Detect when some players don't join a matchmaker game

- server/games/game.py
The profiling data shows that `is_visible_to_player` is causing a bit more load than necessary. This function is called often, and was calling the game's `players` property which would recompute the set of players in the game. This was generating millions of calls to other parts of the code, which can all be avoided by using `self._connection` instead.
I also went ahead and refactored `players` to get rid of one redundant call to `get_player_option`.
> Optimization based on profiling data

- server/db/models.py
- server/gameconnection.py
- server/games/game.py
- server/lobbyconnection.py
- tests/unit_tests/test_game.py
- tests/unit_tests/test_gameconnection.py
- tests/unit_tests/test_lobbyconnection.py
Previously it was possible to put non-ascii characters into the game name by changing the name through the in-game lobby. These changes prevent the game name from being set to non-ascii characters from everywhere.
> Allow only ascii characters in game names

- server/ladder_service.py
- tests/conftest.py
- tests/unit_tests/test_ladder_service.py
The map pool selection was still hardcoded to use ladder rating, I must have missed this spot when switching to getting the rating type from the queue.
> Use correct rating type when choosing a map pool

- server/games/game.py
- server/ladder_service.py
- server/matchmaker/algorithm.py
- server/matchmaker/search.py
Before it was difficult to sift through the log output for matchmaker messages because each player object would log both ladder and global ratings, at least one of which would be completely irrelevant. Now we log only the rating that is actually being used by the algorithm.
Here's what a matching lifecycle between two new players looks like now:
```
TRACE    Jan 24  16:07:56 LobbyConnection                << test: {'command': 'game_matchmaking', 'state': 'start', 'mod': 'ladder1v1', 'faction': 'uef'}
TRACE    Jan 24  16:07:56 LobbyConnection                >> test: {'command': 'search_info', 'queue_name': 'ladder1v1', 'state': 'start'}
INFO     Jan 24  16:07:56 LadderService                  Search(ladder_1v1, [Player(test, 1, (2000.0, 125.0))], threshold=0.71, expansion=0.0) started …
```
> Improve matchmaking log messages

- server/ladder_service.py
Adds 10 seconds to the game launch timeout for each connection that a client needs to establish. For example in 2v2, a client needs to connect to 3 other players, so we add 30 seconds to the timeout. The total launch timeouts for each possible game size are summarized below.
| Game Type | Number of Players | Launch Timeout |
| :--------------- | :-----------------------: | ---------------------: |
| 1v1              |               2               |                    0:40 |
| 2v2              |               4               |                    1:00 |
| 3v3              |               6               |                    1:20 |
| 4v4              |               8               |                    1:40 |
| 5v5              |              10              |                    2:00 |
| …
> Increase matchmaker game timeout

- server/matchmaker/algorithm.py
- server/matchmaker/search.py
- tests/integration_tests/test_teammatchmaker.py
- tests/unit_tests/test_matchmaker_queue.py
- tests/unit_tests/test_matchmaker_queue_algorithm.py
This makes random newbie matching apply to any rating type and for any team size. 
Team with at least one newbie and no top-rated players will be matched randomly amongst each other if no quality game is found. However, if there are an odd number of newbie teams, the last newbie team can only match with a non-newbie team that has at least one failed matching attempt. If a team has a top-rated player, that team will not be eligible for random matching at all.
Closes #713
> Feature/#713 Generalize newbie rating adjustments

- server/matchmaker/matchmaker_queue.py
- server/matchmaker/search.py
- tests/data/test-data.sql
- tests/integration_tests/test_game.py
- tests/integration_tests/test_teammatchmaker.py
- tests/unit_tests/test_matchmaker_queue.py
It was not directly the fault of the pop timer, but rather an exception that could sometimes occur during random newbie matching. `CombinedSearch` objects would return a list for `failed_matching_attempts` instead of an integer. This has been fixed and I made sure to add an integration test that covers newbie matching with two solo queue-ers who were placed together by the team creation code. I also wrapped the pop timer loop contents in a try block, since this sort of error should really only be failing the current matching attempt, and not crashing the entire timer loop.
> Fix pop timer crash

- server/games/coop.py
- server/games/game.py
- server/games/typedefs.py
- tests/integration_tests/test_coop.py
- tests/integration_tests/test_game.py
- tests/integration_tests/test_server.py
Seems like these two things were broken:
- FA reports `Expansion` values as 'true' or 'false' now instead of 1 or 0
- Game ending code triggers before `OperationComplete`, and since coop games don't report any results they were getting marked as `UNKNOWN_RESULT`. This wasn't an issue before because they used to be marked as unknown only after having been inserted into the leaderboard.
If you have better ideas for how to solve point 2, let me hear them. Right now I'm overriding `on_game_end` in `CoopGame`, to remove the game result checking, but that leaves a bunch of other code duplicated.
Closes #687
> Issue/#687 Fix coop leaderboards again

- server/db/__init__.py
- server/games/game.py
Can't really test it since it only happens rarely on production and probably only under high load.
Closes #606
> Issue/#606 Rare mysql deadlock

- Pipfile.lock
- tests/conftest.py
- tests/integration_tests/conftest.py
- tests/integration_tests/test_server_instance.py
- tests/unit_tests/conftest.py
- tests/unit_tests/test_game.py
- tests/unit_tests/test_ladder_service.py
- tests/unit_tests/test_matchmaker_queue_algorithm.py
- tests/unit_tests/test_protocol.py
- tests/unit_tests/test_test_utils.py
- tests/utils.py
- Fix flaky tests
- Rewrite hypothesis tests to not use function scoped fixtures
- Update dependencies
To get around the hypothesis limitation of not being able to use function scoped fixtures, I've introduced a few "context" fixtures. These are akin to "factory" fixtures that we have already, except that they return a context manager that will yield an instance of the desired object, and clean it up upon exit. This lets us create test objects for each hypothesis example. To avoid having many layers of `with` statements in these tests, I've also added a decorator for automatically calling these context managers whenever a test function is called. 
There are a few contexts that need to be called with the `request` fixture, which for now can't be auto initialized. With additional …
> Cleanup tests and update dependencies

- .github/workflows/test.yml
I think it wants the full file paths. In coveralls these were just clutter, but codecov needs to map them to files in the repo so it can compare them to the git diff.
> Fixup codecov

- .github/workflows/test.yml
- server/db/models.py
- server/games/coop.py
- server/games/custom_game.py
- server/games/game.py
- server/ladder_service.py
- server/matchmaker/map_pool.py
- server/types.py
- tests/data/test-data.sql
- tests/integration_tests/test_game.py
- tests/integration_tests/test_matchmaker.py
- tests/integration_tests/test_teammatchmaker.py
- tests/unit_tests/test_ladder_service.py
- tests/unit_tests/test_map_pool.py
I went ahead and took a first swing at how supporting generated maps would look like in the server code.
The id for the generated maps is the negative integer of the bytes representing the seed and options. This allows for the map_pool choose maps to still work as intended while removing the possibility of collisions with authored maps in the pool and having a unique id for each generated map.
The current issue is that this would need for the map_version_id to be null in the map_pool_map_version table but that is currently being used as part of a primary key probably need to consult @Brutus5000
> Add generated map support to ladder_service

- server/game_service.py
- server/games/typedefs.py
- server/lobbyconnection.py
- tests/unit_tests/test_game.py
- tests/unit_tests/test_games_service.py
- tests/unit_tests/test_lobbyconnection.py
Remove references to equilibrium
I was able do three things as part of this change set.
- Remove Equilibrium from the `FeaturedModType` enum and all references
- Migrate game class detection out of the `game_service` class
- Update `game_service` tests to pass in a game class since the method signature technically changed
Please let me know if you have any questions or feedback for improvement!
Closes #744
> Remove references to equilibrium #744

- tests/integration_tests/conftest.py
- tests/integration_tests/test_control_server.py
The control server seems to be unable to bind to the default address on github actions?
I guess it's primarily an issue of host name resolution not returning the correct address in github actions ubuntu VM's. So at least in theory binding directly to 127.0.0.1 should solve the issue by avoiding name resolution entirely.
#772
> Fix control server integration tests

- server/core/service.py
- tests/unit_tests/core/test_service.py
Cherry picked from #671. Want this for the renaming feature in the OAuth PR.
> Remove metaclass for service creation

- server/games/coop.py
- server/games/custom_game.py
- server/games/game.py
- tests/unit_tests/test_ladder_service.py
> Add timeout to base game class

- tests/integration_tests/conftest.py
This was the cause of some flaky tests when the server went down.
> Fix tests trying to contact the real hydra server

- server/games/game.py
- tests/unit_tests/test_game.py
> Don't serialize team if it is None

- server/broadcast_service.py
- server/game_service.py
- server/message_queue_service.py
- server/rating_service/rating_service.py
- tests/conftest.py
- tests/integration_tests/test_game.py
- tests/unit_tests/test_game_rating.py
- tests/unit_tests/test_rating_service.py
> Let rating service publish rating changes to RabbitMQ

- Pipfile
- Pipfile.lock
- server.py
- server/config.py
- server/games/game.py
- server/matchmaker/search.py
Uvloop claims to be a faster drop in replacement for asyncio's event loop: https://github.com/MagicStack/uvloop
It would be interesting to see if this would give us any performance improvements. I've set it up so it can be disabled in the config by setting `USE_UVLOOP: false` (server restart required) in case something goes wrong.
Note I haven't set it up to be used during unit tests. Probably the correct way to do that would be with tox, but I haven't used tox before, so I'm not sure how easy it is to set up.
> Use uvloop instead of asyncio default event loop

- server/lobbyconnection.py
- tests/unit_tests/test_lobbyconnection.py
Moves #607 forward (see https://github.com/FAForever/downlords-faf-client/issues/1783#issuecomment-894844963).
Sadly untested because if currently don't have a local environment for running the python server, so i would be glad if somebody else could test that. Sorry.
> Add dummy implementation for client command `match_ready` (#607)

- server/config.py
- server/matchmaker/algorithm/team_matchmaker.py
- server/matchmaker/search.py
- tests/unit_tests/test_matchmaker_algorithm_team_matchmaker.py
Normalizes the time bonus accumulation. So now a full game will accumulate the same time boni regardless of team size or premade parties. This increases mainly the 4v4 game quality, because it is not so dominated anymore by the time boni.
Also allows the game quality to be negative. This discourages really bad matches.
> Fix game quality calculations

- server/protocol/qdatastream.py
- server/protocol/simple_json.py
- server/servercontext.py
- tests/unit_tests/test_protocol.py
The SimpleJson protocol would throw JSONDecodeError's whenever a client disconnected because it would pass `""` to json.loads.
> Check for clean disconnects and raise DisconnectedError

- server/config.py
- server/matchmaker/algorithm/team_matchmaker.py
- tests/data/test-data.sql
- tests/unit_tests/test_matchmaker_algorithm_team_matchmaker.py
Here we go again...
When looking at some real games I noticed two problems with the current implementation:
- If the uniformity and the fairness are both very bad (close to 0) and at least one is negative, we get a better score (slightly below 0) than if one is negative and the other one is really good (close to 1). Then we get a score that is way more negative.
- We don't care so much if the rating disparity is exactly zero, but we want to discourage games where uniformity or fairness are way off.
We can fix the first one by not multiplying but adding uniformity and fairness. That way one getting worse will always worsen the game quality.
For the second one we can simply square the penalty for deviating from the ideal values. This makes small errors smaller and increases big errors.
With …
> Change game quality calculations

- server/db/__init__.py
- server/gameconnection.py
- server/games/game.py
- server/ladder_service.py
- server/matchmaker/pop_timer.py
- server/oauth_service.py
- server/stats/game_stats_service.py
- tests/integration_tests/test_oauth_session.py
- tests/unit_tests/test_database.py
- tests/unit_tests/test_gameconnection.py
- tests/unit_tests/test_oauth_service.py
- tests/unit_tests/test_oauth_session.py
- Better logging of errors with reported JsonStats
- Error handling if hydra jwk endpoint is unreachable
- Better handling of game timeout
- Fix error in `deadlock_retry_execute` exception handler
> Fix misc errors that show up in the logs

- .pre-commit-config.yaml
- Pipfile.lock
- README.md
- setup.cfg
Hopefully this will help the maintainers spend less time on reviewing some trivial things like typos and good code style.
At the moment. some basic hooks have been added, although [there are a lot more of them](https://pre-commit.com/hooks.html). Perhaps you'd like to add something.
Also not sure about max-line-lenght (`E501` in `flake8`'s black list). But for now probably it is better to keep it as there are a lot of changes to be done to fix this.
There is the [pre-commit GitHub Action](https://github.com/pre-commit/action) that also could be added to the checks.
> Add pre-commit configuration to the project

- server/games/game.py
- server/players.py
- server/rating.py
- tests/unit_tests/test_rating.py
I had a look at the server profile generated after the last update, and it looks like the rating initialization was being called an excessive amount. This is mostly because it gets invoked both when generating `game_info` as well as `player_info` messages. 
In the `game_info` messages it would be called even if the rating data wasn't actually needed, just because it had been easier to write that ways. Now, it checks whether rating enforcement is enabled first and only queries the rating if it is. I also added some caching to the rating computation itself so that the queries generated by the `player_info` message creation will now short circuit the majority of the time.
> Optimize rating initialization

- .github/workflows/test.yml
- server/db/models.py
- server/ladder_service.py
- server/matchmaker/matchmaker_queue.py
- server/types.py
- tests/conftest.py
- tests/data/test-data.sql
- tests/integration_tests/conftest.py
- tests/integration_tests/test_game.py
- tests/integration_tests/test_matchmaker.py
- tests/unit_tests/test_ladder_service.py
- tests/unit_tests/test_matchmaker_queue.py
Loads additional params from the database and parses out game options to send in the game_launch message. My goal is for the `params` column to closely resemble the `gameInfo` table in the lua code. So something like this:
```json
{
"GameOptions": {
"FogOfWar": "explored",
"UnitCap": 1000,
"Share": "FullShare",
},
"GameMods": {}
}
```
But it could always be expanded in the future.
Requires https://github.com/FAForever/db/pull/285
Closes #824
> Issue/#824 support for GameOptions in matchmaker queues

- server/oauth_service.py
- tests/integration_tests/test_login.py
This asserts that the oauth token contains the lobby scope before allowing a player to login. This allows for players to be banned from just the game service. All oauth tokens from the clients currently have the lobby scope
> Check for lobby scope in token during login

- server/types.py
- tests/data/test-data.sql
- tests/integration_tests/test_matchmaker.py
- tests/unit_tests/test_ladder_service.py
Only enforce that the param size needs to be a multiple of 64 as specified by the map name encoding of the generator
> Allow map size of the generator params to be non power of 2

- server/message_queue_service.py
- tests/integration_tests/conftest.py
- tests/integration_tests/test_message_queue_service.py
Fixes #853
As long as we do not have any session-related data,
all exchanges and queues should be durable to avoid
data loss on server restart.
> Make RabbitMQ exchanges durable

- .github/workflows/test.yml
- server/games/game.py
- server/games/typedefs.py
- tests/unit_tests/test_game.py
I think we should add a validity state to the database just for this.
Closes #838
> Issue/#838 Check for manual unrank game option

- server.py
- server/db/__init__.py
- server/db/models.py
- server/db/typedefs.py
- server/game_service.py
- server/gameconnection.py
- server/games/game.py
- server/games/game_results.py
- server/games/typedefs.py
- server/ladder_service.py
- server/lobbyconnection.py
- server/metrics.py
- server/player_service.py
- server/rating_service/rating_service.py
- tests/conftest.py
- tests/data/test-data.sql
- tests/integration_tests/test_coop.py
- tests/integration_tests/test_game.py
- tests/integration_tests/test_matchmaker.py
- tests/integration_tests/test_server.py
- tests/integration_tests/test_teammatchmaker.py
- tests/unit_tests/test_database.py
- tests/unit_tests/test_game.py
- tests/unit_tests/test_game_rating.py
- tests/unit_tests/test_gameconnection.py
- tests/unit_tests/test_laddergame.py
- tests/unit_tests/test_lobbyconnection.py
- tests/unit_tests/test_rating_service.py
- tests/utils.py
It works mostly the same but is more up to date and will hopefully play nicer with python 3.9. As a result of some of the API differences, I had to refactor some of the uses of the `Row` object. I ran into a cyclic dependency issue when importing `db.models` from `GameService`. Somehow this causes a cycle `models -> game -> CoopGame -> models`, and I'm not entirely sure why I don't see that problem when importing the models anywhere else, but I refactored the typedefs to be their own module that can be imported from anywhere in the server without causing cycles. I also refactored random code style stuff as I found it.
Closes #773 
Might also close #657
> Issue/#773 refactor database wrapper to use sqlalchemy engine instead of aiomysql 

- server/gameconnection.py
- server/lobbyconnection.py
- tests/integration_tests/test_game.py
- tests/integration_tests/test_matchmaker.py
- tests/integration_tests/test_teammatchmaker.py
- tests/unit_tests/test_gameconnection.py
- tests/unit_tests/test_lobbyconnection.py
The messages happen after you click to join or host a game and the client sends `game_host` but then never actually starts FA after getting the `game_launch` message. While I do consider this a client bug, this behavior is more correct and is needed for the matchmaker timeout stuff.
> Fix "Can't xxxx game while in state xxxx" messages

- server/config.py
Looking at the logs has showed that currently the timer reduction gets almost never triggered. Reducing the desired matches to 2.5 should allow queue times to reduce to about two minutes during busy weekend hours.
> Reduce desired matches for pop timer

- server/game_service.py
- server/ladder_service/ladder_service.py
- server/matchmaker/matchmaker_queue.py
- server/metrics.py
Closes #877 
Not sure if I put the MatchLaunch enum in the best file.
Can Prometheus deal with the changed metric names and labels?
My idea with the game quality metrics is to display dots in a timeline graph instead of using the heatmap. This should enable us to compare the different queues in one graph.
> Add more prometheus metrics

- server/game_service.py
- tests/unit_tests/test_games_service.py
If the game_stats table is empty, the creation of new games will fail. Picking the max(id) of game_stats is null,
but incrementing null by 1 throws an error.
> Set game_id_counter to 0 if no games

- server/game_service.py
- server/matchmaker/matchmaker_queue.py
- server/metrics.py
We need histograms instead of gauges to be able to properly display the match quality in Grafana. The number of currently active matchmaker games is also nice to have.
> Refine matchmaker metrics

- server/geoip_service.py
The sixth column is for seconds, so the extra zero caused the cronjob to run everyday at three seconds after midnight instead of every wednesday at midnight
> Fix GeoIP cronjob schedule

- server/ladder_service/violation_service.py
- tests/integration_tests/test_matchmaker.py
- tests/integration_tests/test_matchmaker_violations.py
- tests/unit_tests/test_violation_service.py
The issue isn't with parties but with relogs. Since I refactored the `Player` objects to no longer hash by id because it was causing confusing and incorrect behavior in other parts of the code, using `Player`s as keys directly made the violation service think you were a different player after you relogged. Tracking by player id explicitly should fix this.
Closes #931
> Issue/#931 Violation tracking fix

- server/matchmaker/algorithm/team_matchmaker.py
- tests/unit_tests/test_matchmaker_algorithm_team_matchmaker.py
The recent fix to the minority bonus created a new problem. When there are many high rated people in the queue this bonus actually allows games of too low quality like this one:
This is because the bonus is uncapped and grows with the power of 4. This was originally intended to shape the curve in the 0..1 range, but becomes a problem at extreme ratings.
A cap on the bonus allows to prevent this while not changing the bonus for moderately high rated people.
> Cap minority bonus

- server.py
- server/__init__.py
- server/config.py
- server/servercontext.py
- tests/integration_tests/test_game.py
- tests/integration_tests/test_matchmaker.py
- tests/unit_tests/test_servercontext.py
This enables us to set up the lobby ports using the yaml config file. It's not entirely dynamic in that changing the config will still require a server restart to take effect (mostly because it was going to be a little complicated to implement and I felt like it wasn't worth it). This will let us turn off the legacy QDataStream socket whenever we feel like it's time without needing to make a code change.
I also have some plans for a subsequent PR to add a 'v2' port that will be enabled in dev/test configs but not in prod, so we can start deploying some breaking protocol changes running side by side with the stable version to develop against.
> Configure server contexts through yaml config

- Pipfile
- Pipfile.lock
- main.py
- server/__init__.py
- server/config.py
- server/servercontext.py
- tests/integration_tests/conftest.py
- tests/integration_tests/test_server.py
Adds a new option to the `LISTEN` config which can enable the PROXY protocol for the given socket. This allows the lobby server to be placed behind a TCP proxy and still receive correct IP information for logging and GEOIP location. When a socket is placed into PROXY mode it should ONLY be accessed via the proxy. Direct traffic to the socket must be blocked by a firewall.
Proxy mode supports both v1 and v2 of the PROXY protocol which will be automatically detected from the connection headers.
> Add support for the PROXY protocol

- tests/conftest.py
- tests/integration_tests/test_game.py
- tests/integration_tests/test_matchmaker.py
- tests/integration_tests/test_message_queue_service.py
- tests/integration_tests/test_servercontext.py
- tests/integration_tests/test_teammatchmaker.py
- tests/unit_tests/test_custom_game.py
- tests/unit_tests/test_game.py
- tests/unit_tests/test_game_rating.py
- tests/unit_tests/test_game_results.py
- tests/unit_tests/test_gameconnection.py
- tests/unit_tests/test_laddergame.py
- tests/unit_tests/test_message_queue_service.py
Change game fixtures to be async to guarantee that event loop exists when the `Game` constructor is called, and ensure that sockets are closed in `ServerContext` tests.
> Cleanup tests

- server/rating_service/rating_service.py
- server/rating_service/typedefs.py
- tests/integration_tests/test_game.py
right now the league service has no way of knowing which game is associated with a rating change message. This is a problem because the client can't know which entry to fetch from the league score journal when the client wants to display a specific replay.
We add the game id to the message to fix this.
> Add game id to rating change message

- DEVELOPMENT.md
- server/lobbyconnection.py
This will prevent the logs from being filled with warnings about failing to update NickServ password whenever someone logs in.
Closes #977
> Issue/#977 Remove IRC password functionality

- .github/workflows/lint.yml
This should help to make sure the pipfile.lock stays properly updated. Pipenv will verify that the hash in the pipfile.lock matches certain data from the Pipfile, so if a dependency is added or removed in the Pipfile, the pipfile.lock needs to be updated as well.
> Add `pipenv verify` to lint actions
