FAForever/server

FAGamesServerThread.py

i am currently not able to test this.

send p2preconnect when hashmark in title

---

README.md

Now understandable by people that like me don't do python dev
and have negative IQ when it comes to system administration

Improve installation and test running instructions

---

README.md
src/lobbyconnection.py
tests/unit_tests/test_lobbyconnection.py

CREATE_ACCOUNT tests are missing and waiting on #23
Does the email sending working?
I had encoding problems on my first mock test here:
`base64.b64encode(str(uid))`

Tests for handle_action

---

src/games/game.py
src/games/gamesContainer.py
src/games/ladderGamesContainer.py

I noticed the field was not defined and then that while it was written to,
nothing used it. So I removed the setter and the calls to it. Also removed
the unused constructor parameter. As far as I can tell, nothing was calling
the constructor with the full arg list, so no further changes are needed.

Remove hostLocalPort from Game

---

README.md

with https://github.com/FAForever/client/commit/d51d31dfe2b4571da96cbe7ba6f38609d561216e#diff-fec04f0d6c9f34888f0f19fa260ce0f6

Map Selection Removed

---

server/lobbyconnection.py

Add "Custom Missions" to allowed coop map types

---

tests/data/db-fixtures.sql
tests/integration_tests/test_server.py

Changed the insert statements to SHA2(..., 256) the test-passwords.

Login data: test user passwords now get correctly hashed

---

tests/unit_tests/test_game.py
tests/unit_tests/test_gameconnection.py

fix tests related to enforce_rating

---

server/stats/game_stats_service.py

More robust stats interpretation

---

server/lobbyconnection.py

Do not throw exception on expired bans

---

server/games/game.py
tests/data/db-fixtures.sql

See https://github.com/FAForever/db/pull/24

Remove table_map_unranked

---

requirements.txt

No more gambling. This also resolves the docker caching issue.

Fix faftools version by commit ID

---

server/connectivity.py
server/db/logging_cursor.py
server/gameconnection.py
server/games/game.py
server/lobbyconnection.py
server/matchmaker/matchmaker_queue.py
server/matchmaker/search.py
server/natpacketserver.py
server/servercontext.py
server/stats/achievement_service.py
server/stats/event_service.py
server/stats/game_stats_service.py
tests/unit_tests/test_game.py

This gives a small performance increase due to deferring the actual string building part until it's really needed

Remove use of format() when logging

---

server/player_service.py

There is no call to `update_rating` in the code

Remove unused method update_rating

---

server/games/game.py
tests/unit_tests/conftest.py
tests/unit_tests/test_custom_game.py
tests/unit_tests/test_game.py

Fixes #202 (Unranked when FFA or uneven teams)

Unrank FFA, uneven teams and unreported games

---

server/games/game.py
tests/unit_tests/test_laddergame.py

This is exactly why one should never modify function arguments

Fix #248 ladder rating sometimes not updated

---

server/lobbyconnection.py
server/servercontext.py
tests/integration_tests/test_servercontext.py

#244 record active user agents on statsd

---

server/game_service.py

Fix #275 make equilibrium ranked

---

server.py

Will add log level and logger name to log output.

Add log formatting

---

server/__init__.py

Fixes #295.
Signed-off-by: Igor Kotrasinski <i.kotrasinsk@gmail.com>

Show 'friends' games to host as well

---

server/lobbyconnection.py

Add first uid and then user assignment
see https://github.com/FAForever/db/pull/114

Add uid first and then uid assignment

---

server/lobbyconnection.py

And order bans by descending expiry order.
Fixes FAForever/db#123

Don't require a single login result

---

server/lobbyconnection.py

Fix remove_avatar

---

server/config.py
server/lobbyconnection.py

Code runs, so it's valid python, but I'm still unable to set up Python server locally.

Forced steam linking for users registered after a certain date

---

.travis.yml
server.py
server/__init__.py
server/game_service.py
server/gameconnection.py
server/games/game.py
tests/unit_tests/test_game.py
tests/unit_tests/test_lobbyconnection.py

This PR is linked to https://github.com/FAForever/db/pull/173
( Please delete my previous PR https://github.com/FAForever/server/pull/348 )
Added 3 new unrank possibilities
- Map not in the vault triggers BAD_MAP
- HAS_AI for games with at least one AI
- MULTI_TEAM for 2v2v2 or 3v3v3 or this kind of pseudo-ffaesque configuration
I wrote unit tests for the two new validation marks aswell.

More unrank conditions + Few improvement

---

server/config.py
server/matchmaker/matchmaker_queue.py
server/matchmaker/search.py
tests/unit_tests/test_matchmaker_queue.py

@Exotic-Retard 
Implemented a system where new players (<10 games, or any threshold specified by ENV vars) get a rating adjustement for matchmaking so that matchmaking becomes more fair

Implementing exotic newb-friendly matchmaking

---

server/lobbyconnection.py

https://github.com/FAForever/db/pull/166

Added last_login update on login

---

server/gameconnection.py

Hotfix for games being unranked because of HAS_AI / AIReplacement setting being wrongly filtered

Fix unrank ai

---

tests/unit_tests/test_game.py

If game.clear_data() is not awaited, the result can be uncertain. As an async function it is always called with await everywhere in code, but here. Fixing it prevents the unit tests to randomly fail.

Fix test_game.py unawaited clear_data()

---

server/games/game.py
server/stats/game_stats_service.py
tests/unit_tests/test_game.py
tests/unit_tests/test_game_stats_service.py

New version of https://github.com/FAForever/server/pull/262 that replaces #257 
Credit to @micheljung  or @Crotalus , I'm not sure. 
Closing theirs.

get_army_result now takes the most reported result

---

server/game_service.py

Someone probably moved the database around at some point and forgot to update the server

Fixed ranked mods being unranked

---

server/player_service.py

Fixes #323 
Not exactly sure how the client handles newlines but presumably this will look better than it did before.

Issue/#323 Clean up spacing and <br>'s

---

Dockerfile
requirements.txt
server/__init__.py
server/abc/base_game.py
server/config.py
server/connectivity.py
server/control.py
server/db/__init__.py
server/fake_statsd.py
server/game_service.py
server/games/__init__.py
server/matchmaker/__init__.py
server/matchmaker/search.py
server/natpacketserver.py
server/players.py
server/protocol/__init__.py

Removed `-f http://content.faforever.com/wheel/` from `requirements.txt` because this page is a 403 error.
Upgraded `aiohttp` as #292 is no longer relevant.

Cleanup dependencies and imports

---

server/config.py
server/control.py

Removed the POST routes to kick players as they're no longer needed, turned the control server into something fancier. 
One day maybe we can make something really interesting out of it - for the moment I think this is enough, and we may find some use for it as there's no real way ATM to look at what the python server is doing from the outside.

Control server now displays some stats, removed POST route to kick

---

server/control.py

This prevents a few warnings from spamming the console

Add unused request arguments to control server routes

---

server/lobbyconnection.py

Apparently this is going to be implemented in the API. It has never worked on prod (because the function wasn't awaited) so I don't think it has ever been used.

Remove deprecated tutorials section code

---

requirements.txt
server/db/models.py
server/gameconnection.py
server/games/game.py
server/ladder_service.py
server/lobbyconnection.py
tests/data/test-data.sql
tests/integration_tests/test_server.py
tests/unit_tests/conftest.py
tests/unit_tests/test_lobbyconnection.py

That's what you're supposed to do with FIXME's right? Fix them, not stare at them and decide someone else will probably do it later.
I don't think there is a way to change the days/months/weeks parameter in SQL interval without doing string formatting. As far as I know it isn't meant to be a dynamic parameter. The proper solution would be to always use `DAY` and have the client convert weeks/months to days.
Also it turns out GameConnection doesn't even need PlayerService!

FIXME and TODO hunting

---

server/db/models.py
server/lobbyconnection.py
server/player_service.py
tests/data/test-data.sql
tests/unit_tests/test_player_service.py

Related to #399, but note that these tests only cover `fetch_player_data` and are therefore not comprehensive. More work remains to be done.
* Combined a bunch of sql queries into a single statement using the expression language.

Add some tests for PlayerService

---

server/db/models.py
server/gameconnection.py
tests/unit_tests/test_gameconnection.py

The server now uses the new report system instead of the teamkill-only report one

Report system integration

---

server/ladder_service.py
server/lobbyconnection.py
tests/unit_tests/test_matchmaker_queue.py

This should help make more sense of the prod logs

Debug Ladder: Add some additional logging statements

---

server.py
server/decorators.py

Closes #437 
Logs will now look like this:
```
DEBUG    Jun 02  07:41:17 GameService                    Loading featuredMod faf
INFO     Jun 02  07:41:17 aiomysql                       SELECT updates_faf_files.fileId, MAX(updates_faf_files.version) FROM updates_faf_files LEFT JOIN updates_faf ON updates_faf_files.fileId = updates_faf.id GROUP BY updates_faf_files.fileId
```

Issue/#437 Add timestamps to logs

---

server/game_service.py
server/games/game.py
tests/unit_tests/test_game.py

These used to be used by the clients for updating files, but now the clients use the API.

Removed featured_mod_versions from game_info messages

---

Pipfile.lock
server/config.py

Old stuff that is no longer used

Remove unused config variables

---

README.md

Grammar fixes to readme

---

server/fake_statsd.py
server/lobbyconnection.py
tests/integration_tests/test_server.py

- Collect number of failed logins as well as succeeded
- Tag hosted games with the game mode

Increase metrics collection

---

server/db/__init__.py
server/game_service.py
server/gameconnection.py
server/games/game.py
server/ladder_service.py
server/lobbyconnection.py
server/matchmaker/search.py
server/player_service.py
server/players.py
server/rating.py
tests/conftest.py
tests/unit_tests/test_custom_game.py
tests/unit_tests/test_game.py
tests/unit_tests/test_gameconnection.py
tests/unit_tests/test_ladder.py
tests/unit_tests/test_laddergame.py
tests/unit_tests/test_lobbyconnection.py
tests/unit_tests/test_matchmaker_queue_algorithm.py
tests/unit_tests/test_player_service.py
tests/unit_tests/test_players.py
tests/utils.py

This allows us to remove a few DB clearing methods and queries.

Auto-rollback DB changes after every test

---

tests/integration_tests/test_matchmaker.py

Closes #480 
Looks like the code already marks the queue as dirty when a search is cancelled.

Add test for receiving matchmaker updates after queue cancel

---

server/geoip_service.py
server/timing/timer.py
tests/unit_tests/test_geoip_service.py

The intent is that a server admin might manually supply the file in case it is unavailable from maxmind for whatever reason.
Would be nice to have right now so it might be nice to have in the future.

Periodically check if a new database file has appeared

---

server/config.py
server/lobbyconnection.py
tests/integration_tests/test_server.py
tests/unit_tests/conftest.py
tests/unit_tests/test_gameconnection.py
tests/unit_tests/test_lobbyconnection.py

Adding some unit tests for ICE (which @Geosearchef promised me he would write, but never did).

Ice unit tests

---

server/ladder_service.py
server/lobbyconnection.py
server/types.py
tests/integration_tests/test_matchmaker.py
tests/unit_tests/test_types.py

Add options to `launch_game` that allow setting parameters which can't be read from the Game class.
Closes #527

Issue/#527 fix game_launch options

---

.travis.yml
Pipfile
README.md
scripts/pipenv_run_tests.sh
tests/data/test-data.sql

Move all `test-data.sql` into `tests/data/test-data.sql` and use faf-stack version `20.2.7` in Travis.
Necessary for #543

Bump faf stack version in Travis to 20.2.7

---

.travis.yml
Dockerfile
server.py
server/metrics.py
tests/integration_tests/test_game.py

Add build info to metrics

---

server/games/game_rater.py
tests/unit_tests/test_game_rater.py

Completely reworks the decision flow in `GameRater`, the most prominent change being that `DEFEAT` vs `UNKNOWN` is no longer resolved to `DEFEAT` vs `VICTORY` but rather unranked.
Decision flow is now looks at the outcomes of all players on both teams (instead of resolving player outcomes to a single outcome per team first) and proceeds as follows:
1. Did someone claim `VICTORY`?
- If no, proceed to 2. 
- If players on both teams did, unrank.
- Otherwise award victory.
2. Did someone claim `DRAW` or `MUTUAL_DRAW`?
- If no, proceed to 3.
- If players on both teams did, resolve to draw.
- If only players on one team did, unrank.
3. Does someone have `UNKNOWN` or `CONFLICTING` outcome?
- If yes, then we can't decide the outcome, unrank.
- If no, then every player has `DEFEAT`, resolve to …

Unranking Games with Ambiguous Outcome

---

server/lobbyconnection.py
server/protocol/qdatastreamprotocol.py
tests/unit_tests/test_lobbyconnection.py

Reordering some things in case of exceptions, but I don't think this will fix anything.

Refactor abort

---

server/gameconnection.py
server/games/game.py

Adding some more logging to help figure out why some exceptions are thrown

More exception logging

---

server.py
server/core/dependency_injector.py
tests/unit_tests/core/test_dependency_injector.py

Had a mistake in the tests and some things were not merged correctly

Fix service creation

---

server/db/models.py
server/gameconnection.py
server/lobbyconnection.py
tests/integration_tests/test_modvault.py

In my quest to understand more SQL and SQLAlchemy I converted most of the queries that would execute a hardcoded string, into pure sqlalchemy.
There are some cases in which I'm not completely confident in the test coverage of these statements, mostly where concerning the modvault.

More SQLAlchemy

---

server/lobbyconnection.py
tests/integration_tests/test_server.py

Issue #571 - Update player object when new avatar is selected

---

Pipfile.lock
server/gameconnection.py
tests/conftest.py
tests/integration_tests/test_server.py
tests/unit_tests/test_gameconnection.py

- Store all game options in the game options dictionary.
- Remove warning for unused game options.
- Remove workaround for `AIReplacement` on/off state.
- Make sure only the host can configure the game.
- Update dependencies.

Refactor game options

---

server/games/game.py
tests/integration_tests/test_game.py

Luckily it's a 1 line fix.
Fixes #575.

Issue #575 - Game end time STILL not quite right

---

.dockerignore
.travis.yml

Also bump to db version 93.
Closes #579.

Travis pull from faf-db directly

---

CONTRIBUTING.md
README.md
tests/conftest.py

Since there have been a number of new contributors recently, I have realized it would be a lot easier for people to start contributing if the readme was better. I added some more details about running tests and added a `CONTRIBUTING.md` file.

More readme updates

---

server/ladder_service.py
tests/data/test-data.sql
tests/unit_tests/test_ladder_service.py

Potentially fixes #624 
I.E. I see no reason why @Askaholic's proposed [fix](https://github.com/FAForever/server/issues/624#issuecomment-655192848) _wouldn't_ work.

Fix problems with no repetition code

---

server/stats/game_stats_service.py
tests/unit_tests/test_game_stats_service.py

Fix game stats division by zero

---

README.md

Does what it says and says what it does.

Add issuehunt link to readme

---

server/ladder_service.py
tests/unit_tests/test_ladder_service.py

Issue/#581 Remove hardcoded ladder1v1 queue and map pool

---

integration_tests/conftest.py
integration_tests/fafclient.py
integration_tests/test_game.py
integration_tests/test_login.py
integration_tests/test_matchmaking.py
integration_tests/test_server.py
server/servercontext.py

Fixes the achievements test and adds a few tests for some of the one off commands.

Improve integration tests

---

server/gameconnection.py
tests/unit_tests/test_gameconnection.py

#663 - Phantom games report format

---

server/lobbyconnection.py
tests/unit_tests/test_lobbyconnection.py

#693 launch rating type

---

server/rating_service/rating_service.py
tests/unit_tests/test_rating_service.py

Fixes #658
Though not sure if the data is initialized completely in unit tests

#658 - ensure rowcount is not empty

---

server/ladder_service.py
tests/unit_tests/test_ladder_service.py

Randomizes players start spot, but makes sure to randomize both teams in the same way, i.e. if player 1 on team 1 gets moved to slot 2, then player 1 on team 2 will be moved to slot 3, the opposing slot. Note that it does this after choosing the game name, so the party leader will still always appear in the game title.
Closes #700

Shuffle teams before assigning start spots

---

integration_tests/test_matchmaking.py

A couple of things that I forgot to update in previous PR's.
- Host does not always get map position 1 because it is now randomized
- No search_info stop message for the queue if a match was found

Fix integration tests

---

server/ladder_service.py
tests/unit_tests/test_ladder_service.py

Update matchmaker learning popup message and tests

---

.github/workflows/build.yml

Seems like I managed to get everything working.
- Fixed build_args parameter name
- Trigger only once per release (on publish)
- Get the github tag name correctly

Fix github release action

---

.github/workflows/test.yml
setup.cfg

It's pointless, codacy is better

Remove flake8 github action

---

server/stats/unit.py

- #735 Fixed the Czar Unit Bp set as mavor
- Added Salvation Under Experimental

Fixed Unit Bp & Updated Experimentals

---

tests/integration_tests/test_game.py

Increase timeout in `client_response`

---

server/games/game.py
tests/integration_tests/test_teammatchmaker.py
tests/unit_tests/test_game.py

Don't skip some checks when playing featured mods other than faf and ladder1v1.
Closes #739

Issue/#739 Validity checks for featured mods

---

.github/workflows/doc.yml
.github/workflows/test.yml
Pipfile
Pipfile.lock
server/abc/__init__.py
server/api/__init__.py
server/games/__init__.py
server/ice_servers/__init__.py

Setting up auto documentation to hopefully provide something semi useful for contributors of other FAF projects. In this PR I'm just setting up the infrastructure surrounding the docs, and not working on the docs themselves. Once I have it set up I want to work particularly on making sure there is some useful documentation on protocol messages.
#482

Add auto documentation with pdoc3

---

server/matchmaker/matchmaker_queue.py
tests/integration_tests/test_matchmaker.py
tests/unit_tests/test_lobbyconnection.py

Closes #699.
Not sure if these were the kinds of tests you had in mind, let me know!

Feature/#699 Add queue_pop_time_delta to MatchmakerQueue representation

---

tests/conftest.py

Issue/#790 Nightly test deadline

---

.github/workflows/test.yml

Might be an issue with the latest version

Fix github actions rabbitmq service failing to start

---

tests/integration_tests/test_server.py

Should fix `test_game_info_sent_to_friends`

Fix flakey integration test

---

server.py

This will make it easier for me to tell logs apart as I'm starting to accumulate quite a large number of log files.

Add some system information to the logs including lobby version

---

server/games/ladder_game.py
tests/unit_tests/test_game_rating.py
tests/unit_tests/test_laddergame.py

We set them in the ladder_service

Remove ladder game default args

---

.github/codecov.yml
.github/workflows/test.yml
Pipfile

Not 100% sure about disabling the codecov comment because as I recall the only reason I had it enabled was because sometimes the statuses wouldn't show up with the comment disabled. Maybe codecov has fixed this bug by now though.

Improve CI

---

server/gameconnection.py
server/games/game.py
server/games/ladder_game.py
server/ladder_service.py
tests/unit_tests/test_custom_game.py
tests/unit_tests/test_game.py
tests/unit_tests/test_game_rating.py
tests/unit_tests/test_gameconnection.py
tests/unit_tests/test_ladder_service.py
tests/unit_tests/test_laddergame.py

#873 
I's not unlikely that the cancellation doesn't happen at the ideal place

Cancel matches if someone closes the game

---

DEVELOPMENT.md
README.md

Adds some more information about dev setup to the readme. Honestly this might be better placed in its own document at some point because it's getting quite extensive.

Issue/#860 Update README

---

server/games/game.py
tests/unit_tests/test_game.py

The game ending logic could be triggered multiple times simultaneously. Adding a lock ensures that the game state is checked in serial so the game ending logic won't trigger more than once.
Closes #903

Issue/#903 Fix games being rated multiple times

---

server/ladder_service/violation_service.py
tests/unit_tests/test_ladder_service.py

Makes the matchmaker wording slightly less alarming

Matchmaker violation wording change

---

server/config.py
server/db/models.py
server/ladder_service/ladder_service.py
server/matchmaker/algorithm/bucket_teams.py
server/matchmaker/algorithm/matchmaker.py
server/matchmaker/algorithm/stable_marriage.py
server/matchmaker/algorithm/team_matchmaker.py
server/matchmaker/matchmaker_queue.py
server/metrics.py
tests/data/test-data.sql
tests/integration_tests/test_teammatchmaker.py
tests/unit_tests/test_ladder_service.py
tests/unit_tests/test_matchmaker_algorithm_bucket_teams.py
tests/unit_tests/test_matchmaker_algorithm_stable_marriage.py
tests/unit_tests/test_matchmaker_algorithm_team_matchmaker.py
tests/unit_tests/test_matchmaker_queue.py

This is implementing the changes discussed in this thread: https://forum.faforever.com/topic/4945/allow-us-to-pick-rating-brackets-for-tmm/58
Additionally we lower the queue pop timer to provide a better user experience.

Tune matchmaker

---

.github/workflows/build.yml
.github/workflows/doc.yml
.github/workflows/test.yml

Also makes some other updates to actions to fix deprecation warnings.
Closes #878

Issue/#878 Use MariaDB in github actions

---

server/games/game.py
server/games/game_results.py
tests/unit_tests/test_game.py

Issue/#936 Remove mutual draws

---

Pipfile.lock
server/party_service.py
server/servercontext.py
tests/integration_tests/test_servercontext.py

Preparing for next release
Closes #935

Update dependencies and other small things

---

.github/workflows/test.yml
README.md

Maybe it just works?
Closes #876

Issue/#876 Use rabbitmq 3.9

---

server/servercontext.py
tests/integration_tests/conftest.py
tests/integration_tests/test_server.py

Bumped the max buffer size to 10 MiB. Hopefully this will be enough, I'm not sure what the max message size is that we see.
I'll leave the issue open for now so we can monitor the logs if this stops the errors. #939

Issue/#939 Increase asyncio buffer size to allow for longer messages

---

server/gameconnection.py
server/lobbyconnection.py
server/servercontext.py

Some changes that will make it easier to search the logs in grafana, and some changes to make it easier to correlate messages with the player that caused them. I also moved some messages into the info level that happen when people connect/disconnect. This means there will be a log message containing the IP address of everyone who connects:
```
INFO     Jan 07  13:13:13 ServerContext                  LobbyServer[SimpleJsonProtocol]: Client connected from 127.0.0.1:39214
```

More info logging

---

Pipfile
Pipfile.lock
server/game_service.py
server/gameconnection.py
server/games/game_results.py
server/ladder_service/ladder_service.py
server/lobbyconnection.py
server/player_service.py
server/rating_service/rating_service.py
tests/integration_tests/test_coop.py
tests/integration_tests/test_game.py
tests/integration_tests/test_matchmaker.py
tests/integration_tests/test_server.py
tests/integration_tests/test_teammatchmaker.py
tests/unit_tests/test_gameconnection.py
tests/unit_tests/test_laddergame.py
tests/unit_tests/test_lobbyconnection.py
tests/unit_tests/test_rating_service.py

SQLAlchemy 2.0 has some minor breaking API changes. Most of the big stuff was updated already when we went to 1.4.

Update to SQLAlchemy 2.0
